# Generated by Django 5.1.3 on 2024-12-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='depatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepatmentName', models.CharField(max_length=255, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
