# Generated by Django 5.1.3 on 2024-12-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_depatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Contact', models.CharField(max_length=255, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='simage/')),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.depatment')),
            ],
        ),
    ]
