# Generated by Django 5.1.3 on 2024-12-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consulted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
