# Generated by Django 5.1.3 on 2025-01-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_appointment_consulted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consulted',
            field=models.IntegerField(default=0),
        ),
    ]
