# Generated by Django 5.1.3 on 2025-01-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_alter_appointment_consulted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
