from . import views
from django.urls import path

urlpatterns = [
 path('',views.homepage,name='homepage'),
 path('patientsignup',views.patientsignup,name='patientsignup'),
 path('loginpage',views.loginpage,name='loginpage'),
 path('register_patient',views.register_patient,name='register_patient'),
 path(' generate_password',views. generate_password,name=' generate_password'),
 path(' generate_random_string',views. generate_random_string,name=' generate_random_string'),
 path('adminhome',views.adminhome,name='adminhome'),
 path('patienthome',views.patienthome,name='patienthome'),
 path('login1',views.login1,name='login1'),
 path('adddept',views.adddept,name='adddept'),
 path('add_department',views.add_department,name='add_department'),
 path('doctorsignup',views.doctorsignup,name='doctorsignup'),
 path('doctorsignupdetail',views.doctorsignupdetail,name='doctorsignupdetail'),
 path('doctor_list',views.doctor_list,name='doctor_list'),
 path('approve_doctor/<int:id>/', views.approve_doctor, name='approve_doctor'),
 
 path('disapprove_doctor/<int:doctor_id>/', views.disapprove_doctor, name='disapprove_doctor'),
 path('doctorhomepage',views.doctorhomepage, name='doctorhomepage'),
 path('doctoraddadmin',views.doctoraddadmin,name='doctoraddadmin'),
 path(' add_doctor',views. add_doctor,name=' add_doctor'),
 path('booking-form/', views.booking_form, name='booking_form'),
 
 path('create_booking/', views.create_booking, name='create_booking'),
 path('patient_appointments',views.patient_appointments,name='patient_appointments'),
 path('approve_patient/<int:appointment_id>/', views.approve_patient, name='approve_patient'),
 path('disapprove/<int:appointment_id>/', views.disapprove_patient, name='disapprove_patient'),
 path('doctoappointments', views.doctoappointments, name='doctoappointments'),
 path('toggle_consulted/<int:appointment_id>/', views.toggle_consulted, name='toggle_consulted'),
 path('appointment_list',views.appointment_list,name='appointment_list'),
 path('logout/',views.logout,name='logout'),
 path('view-patients/', views.view_patients, name='view_patients'),
 path('delete-patient/<int:patient_id>/', views.delete_patient, name='delete_patient'),
 path('doctors/', views.view_doctors, name='view_doctors'),  # View doctors
 path('doctors/delete/<int:doctor_id>/', views.delete_doctor, name='delete_doctor'),
 path('addpatient',views.addpatient,name='addpatient'),
 path('addnewpatient',views.addnewpatient,name='addnewpatient'),
 path('reset',views.reset,name='reset'),
 path('reset_password',views.reset_password,name='reset_password'),
 path('patient/<int:patient_id>/', views.patient_detail, name='patient_detail'),
 path('view_doctor',views.view_doctor,name='view_doctor'),
 path('about',views.about,name='about'),
 path('doctoreditpage',views.doctoreditpage,name='doctoreditpage'),
 path('update_profile',views.update_profile,name='update_profile'),
 path('reset-password',views.reset_password, name='reset_password'),
 path('repassword',views.repassword,name='repassword'),
 path('get-doctors/<int:department_id>/', views.get_doctors, name='get_doctors'),
 path('display_edit_page',views.display_edit_page,name='display_edit_page'),
 path('edit_profile',views.edit_profile,name='edit_profile'),
path('consulted-patients/', views.consulted_patients_view, name='consulted_patients_view'),
path('instantappointments',views.instantappointments,name='instantappointments'),
path('togglconsulted/<int:appointment_id>/', views.togglconsulted, name='togglconsulted'),
path('patientform',views.patientform,name='patientform'),
 path('departments/', views.display_departments, name='display_departments'),
path('delete_department/<int:department_id>/', views.delete_department, name='delete_department'),
path('patieprofile',views.patieprofile,name='patieprofile'),
path('doctor_profile_view',views.doctor_profile_view,name='doctor_profile_view'),
path('rsetdoc',views.rsetdoc,name='rsetdoc')

]
